const bossArray = [
  { name: 'Vale Guardian', entries: [] },
  { name: 'Spirit Woods', entries: [] },
  { name: 'Gorseval', entries: [] },
  { name: 'Sabetha', entries: [] },
  { name: 'Slothasor', entries: [] },
  { name: 'Bandit Trio', entries: [] },
  { name: 'Matthias', entries: [] },
  { name: 'Escort', entries: [] },
  { name: 'Keep Construct', entries: [] },
  { name: 'Twisted Castle', entries: [] },
  { name: 'Xera', entries: [] },
  { name: 'Cairn', entries: [] },
  { name: 'Mursaat Overseer', entries: [] },
  { name: 'Samarog', entries: [] },
  { name: 'Deimos', entries: [] },
  { name: 'Soulless Horror', entries: [] },
  { name: 'River of Souls', entries: [] },
  { name: 'Statues of Grenth', entries: [] },
  { name: 'Dhuum', entries: [] },
  { name: 'Conjured Amalgamate', entries: [] },
  { name: 'Twin Largos', entries: [] },
  { name: 'Qadim', entries: [] },
  { name: 'Gate of Ahdashim', entries: [] },
  { name: 'Cardinal Adina', entries: [] },
  { name: 'Cardinal Sabir', entries: [] },
  { name: 'Qadim the Peerless', entries: [] },
];

export default bossArray;
